version: "3"

services:
  app:
    build: docker/php
    volumes:
      - ./:/app:cached
      #      - ./docker/php/customini:/usr/local/etc/php/conf.d
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - db
      - mailcatcher
    env_file:
      - .env
    #    environment:
    #      XDEBUG_CONFIG: "remote_host=host.docker.internal"
    # XDEBUG_CONFIG: "remote_host=communitya.host"
    #      PHP_IDE_CONFIG: "docker"
    links:
      - redis
      - db
    expose:
      - "9000"

  webpacker:
    image: node:9-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/true

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app
    links:
      - redis
      - db

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080

  db:
    image: mysql:5.7
    #    hostname: localhost
    volumes:
#      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./docker/db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes",'--requirepass','qwerty']
    hostname: redis
    ports:
      - "6379:6379"
